# Generated by Django 4.1.7 on 2023-03-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Gender',
            new_name='Sex',
        ),
    ]
