# Generated by Django 4.1.7 on 2023-03-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_rename_gender_users_sex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='jain',
        ),
    ]
